Player::Interface
static void Player.Interface.show(String string)
Displays the provided string. string The string to display.
Referenced by Player.Controler.addCorral, Player.Controler.addCreature, Player.Interface.input, Player.Controler.kill, Player.Zoo.kill, Player.Controler.notification, Player.Controler.notification, Player.ZooMaster.options, Player.Controler.removeCorral, Player.Controler.removeCreature, Player.Zoo.removeCreature, Player.Zoo.reviveCreature, Player.Asker.sex.
static String Player.Interface.input(String string)
Takes user input after displaying the provided string. string The string prompt for user input. The user input as a string.
References Player.Interface.show.
Referenced by Player.Asker.corral, Player.Creator.createYourCorral, Player.Creator.createYourCreature, Player.Creator.createYourZoo, Player.Asker.creature, Player.Asker.creature, Player.ZooMaster.options, Player.Asker.sex.