Player::Controler
Zoo Player.Controler.zoo
The zoo
Referenced by Player.Asker.corral, Player.Asker.creature, Player.Zoo.main.
Controler Player.Controler.instance
Contain the Contoler's instance. Is static to allow the use of the Singleton design pattern
boolean Player.Controler.game
True while the game is running, become False when the players ends it.
Referenced by Player.Controler.getInstance, Player.Zoo.main.
Player.Controler.Controler()
Create a new Controler Can only be used by its inner properties
static Controler Player.Controler.getInstance()
Give the instance of the Controler or create one if needed The instance of the Controler
References Player.Controler.game.
Referenced by Player.Asker.corral, Player.Asker.creature, Player.Zoo.main.
void Player.Controler.notification(String notification)
Send a notification to the user (usually used when a Crature has something to say) Allows a separation between the Model and the Interface notification What it has to say
References Player.Controler.notification, Player.Interface.show.
Referenced by Player.Controler.notification, Player.Controler.notification.
void Player.Controler.notification(Object notification)
Send a notification to the user (usually used when a Crature has something to say) Allows a separation between the Model and the Interface notification What it has to say
References Player.Controler.notification, Player.Interface.show.
void Player.Controler.addCreature(Creature creature, Corral corral)
Add a new creature to the Zoo creature The creature to add corral The targeted corral
References Player.Zoo.addCreature, Player.Interface.show.
void Player.Controler.addCorral(Corral corral)
Add a new Corral to the Zoo corral The corral to be added
References Player.Zoo.addCorral, Player.Interface.show.
void Player.Controler.removeCreature(Creature creature)
Remove a creature from the zoo creature The creature to remove
References Player.Zoo.removeCreature, Player.Interface.show.
void Player.Controler.removeCorral(Corral corral)
Remove a Corral from the Zoo corral The corral to remove
References Player.Zoo.removeCorral, Player.Interface.show.
void Player.Controler.kill(Creature creature)
References Player.Zoo.kill, Player.Interface.show.