Game::Creature::Creature
String Game.Creature.Creature.name
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.getName, Game.Creature.Bestiary.Dragon.newBorn, Game.Creature.Bestiary.Kraken.newBorn, Game.Creature.Bestiary.Megalodon.newBorn, Game.Creature.Bestiary.Mermaid.newBorn, Game.Creature.Bestiary.Nymph.newBorn, Game.Creature.Bestiary.Phenix.newBorn, Game.Creature.Bestiary.Unicorn.newBorn, Game.Creature.Oviparian.Oviparian, Game.Creature.Viviparian.Viviparian.
Sex Game.Creature.Creature.sex
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.getSex, Game.Creature.Bestiary.Dragon.newBorn, Game.Creature.Bestiary.Kraken.newBorn, Game.Creature.Bestiary.Megalodon.newBorn, Game.Creature.Bestiary.Mermaid.newBorn, Game.Creature.Bestiary.Nymph.newBorn, Game.Creature.Bestiary.Phenix.newBorn, Game.Creature.Bestiary.Unicorn.newBorn, Game.Creature.Oviparian.Oviparian, Game.Creature.Viviparian.Viviparian.
Weight Game.Creature.Creature.weight
Referenced by Game.Creature.Creature.Creature, Game.Creature.Oviparian.Oviparian, Game.Creature.Creature.toLoseWeight, Game.Creature.Creature.toSwell, Game.Creature.Viviparian.Viviparian.
Height Game.Creature.Creature.height
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.growUp, Game.Creature.Oviparian.Oviparian, Game.Creature.Viviparian.Viviparian.
Age Game.Creature.Creature.age
Referenced by Game.Creature.Creature.age, Game.Creature.Creature.Creature, Game.Creature.Oviparian.Oviparian, Game.Creature.Bestiary.Dragon.run, Game.Creature.Creature.run, Game.Creature.Viviparian.Viviparian.
Hunger Game.Creature.Creature.hunger
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.eat, Game.Creature.Creature.getHunger, Game.Creature.Oviparian.Oviparian, Game.Creature.Creature.toBeHungry, Game.Creature.Viviparian.Viviparian.
Fatigue Game.Creature.Creature.fatigue
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.gettingFatigue, Game.Creature.Oviparian.Oviparian, Game.Creature.Creature.run, Game.Creature.Creature.sleep, Game.Creature.Viviparian.Viviparian.
Health Game.Creature.Creature.health
Referenced by Game.Creature.Creature.Creature, Game.Creature.Creature.heal, Game.Creature.Creature.loseHealth, Game.Creature.Oviparian.Oviparian, Game.Creature.Creature.toString, Game.Creature.Viviparian.Viviparian.
boolean Game.Creature.Creature.isAlive
BirthBehavior Game.Creature.Creature.birthingBehavior
Game.Creature.Creature.Creature(String name, Sex sex, Weight weight, Height height, Age age, Hunger hunger, Fatigue fatigue, Health health)
References Game.Creature.Creature.age, Game.Creature.Creature.fatigue, Game.Creature.Creature.health, Game.Creature.Creature.height, Game.Creature.Creature.hunger, Game.Creature.Creature.name, Game.Creature.Creature.sex, Game.Creature.Creature.weight.
void Game.Creature.Creature.toFly()
Behavior.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.toRun()
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.toSwim()
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.toBeHungry()
References Game.Creature.Creature.hunger, Game.Creature.Creature.loseHealth.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.shout()
Referenced by Game.Creature.Bestiary.Dragon.run, Game.Creature.Creature.run.
void Game.Creature.Creature.loseHealth()
References Game.Creature.Creature.health.
Referenced by Game.Creature.Creature.age, Game.Creature.Creature.toBeHungry, Game.Creature.Creature.toLoseWeight, Game.Creature.Creature.toSwell.
void Game.Creature.Creature.heal()
References Game.Creature.Creature.health.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.gettingFatigue()
References Game.Creature.Creature.fatigue.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.sleep()
References Game.Creature.Creature.fatigue.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.age()
References Game.Creature.Creature.age, Game.Creature.Creature.loseHealth.
void Game.Creature.Creature.growUp()
References Game.Creature.Creature.height.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.toSwell()
References Game.Creature.Creature.loseHealth, Game.Creature.Creature.weight.
Referenced by Game.Creature.Creature.eat.
void Game.Creature.Creature.toLoseWeight()
References Game.Creature.Creature.loseHealth, Game.Creature.Creature.weight.
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.reproduce()
Referenced by Game.Creature.Creature.run.
void Game.Creature.Creature.run()
References Game.Creature.Creature.age, Game.Creature.Creature.fatigue, Game.Creature.Creature.gettingFatigue, Game.Creature.Creature.growUp, Game.Creature.Creature.heal, Game.Creature.Creature.reproduce, Game.Creature.Creature.shout, Game.Creature.Creature.sleep, Game.Creature.Creature.toBeHungry, Game.Creature.Creature.toFly, Game.Creature.Creature.toLoseWeight, Game.Creature.Creature.toRun, Game.Creature.Creature.toSwim.
void Game.Creature.Creature.eat()
References Game.Creature.Creature.hunger, Game.Creature.Creature.toSwell.
String Game.Creature.Creature.getName()
References Game.Creature.Creature.name.
Referenced by Game.Creature.Creature.equals.
Sex Game.Creature.Creature.getSex()
References Game.Creature.Creature.sex.
Hunger Game.Creature.Creature.getHunger()
References Game.Creature.Creature.hunger.
String Game.Creature.Creature.toString()
References Game.Creature.Creature.health.
boolean Game.Creature.Creature.equals(Object o)
References Game.Creature.Creature.getName.