Player::ZooMaster
final int Player.ZooMaster.REFRESH_COOLDOWN
final int Player.ZooMaster.MAX
String Player.ZooMaster.name
Sex Player.ZooMaster.sex
Age Player.ZooMaster.age
int Player.ZooMaster.actions
int Player.ZooMaster.maxActions
Corral Player.ZooMaster.scope
Player.ZooMaster.ZooMaster(String name, Sex sex, Age age)
String Player.ZooMaster.toString()
void Player.ZooMaster.cooldown(Cooldown cooldown)
References Player.ZooMaster.cooldown.
Referenced by Player.ZooMaster.cooldown.
void Player.ZooMaster.options()
References Player.Interface.input, Player.ZooMaster.options, Player.Interface.show.
Referenced by Player.Zoo.main, Player.ZooMaster.options.
void Player.ZooMaster.refreshCooldown()
void Player.ZooMaster.check()
void Player.ZooMaster.clean()
void Player.ZooMaster.feed()
void Player.ZooMaster.move()
void Player.ZooMaster.zoom()
void Player.ZooMaster.add()
void Player.ZooMaster.remove()