Player::Zoo
final int Player.Zoo.MAX
final int Player.Zoo.LOVE_SEASON_DURATION
String Player.Zoo.name
int Player.Zoo.maxCorral
List<Corral> Player.Zoo.corrals
ZooMaster Player.Zoo.zooMaster
Referenced by Player.Zoo.main, Player.Zoo.opening.
List<Pack> Player.Zoo.colony
Referenced by Player.Zoo.spread.
boolean Player.Zoo.loveSeason
Player.Zoo.Zoo(String name, ZooMaster zooMaster)
String Player.Zoo.showOnlyCorrals()
String Player.Zoo.showCorrals()
boolean Player.Zoo.exists(Corral check)
static void Player.Zoo.main(String[] args)
References Player.Controler.game, Player.Controler.getInstance, Player.ZooMaster.options, Player.Controler.zoo, Player.Zoo.zooMaster.
static Zoo Player.Zoo.opening(String name, ZooMaster zooMaster)
References Player.Zoo.zooMaster.
Referenced by Player.Creator.createYourZoo.
String Player.Zoo.showCreatures()
References Player.Zoo.corral.
Referenced by Player.Asker.creature.
int Player.Zoo.countCreatures()
References Player.Zoo.corral.
int Player.Zoo.countCorrals()
Referenced by Player.Zoo.addCorral.
String Player.Zoo.toString()
boolean Player.Zoo.exists(Creature creature)
References Player.Zoo.corral.
Referenced by Player.Zoo.addCreature, Player.Zoo.kill, Player.Zoo.removeCreature, Player.Zoo.reviveCreature.
Corral Player.Zoo.corralOf(Creature creature)
References Player.Zoo.corral.
Referenced by Player.Zoo.kill, Player.Zoo.removeCreature, Player.Zoo.reviveCreature.
void Player.Zoo.addCorral(Corral corral)
References Player.Zoo.corral, Player.Zoo.countCorrals.
Referenced by Player.Controler.addCorral.
String Player.Zoo.corrals()
References Player.Zoo.corral.
Corral Player.Zoo.corral(String string)
References Player.Zoo.corral.
Referenced by Player.Zoo.addCorral, Player.Zoo.addCreature, Player.Zoo.corral, Player.Zoo.corralOf, Player.Zoo.corrals, Player.Zoo.countCreatures, Player.Zoo.exists, Player.Zoo.getCreatures, Player.Zoo.removeCorral, Player.Zoo.showCreatures.
void Player.Zoo.removeCorral(Corral corral)
References Player.Zoo.corral.
Referenced by Player.Controler.removeCorral.
void Player.Zoo.extend(int size)
void Player.Zoo.addCreature(Corral corral, Creature creature)
References Player.Zoo.corral, Player.Zoo.exists.
Referenced by Player.Controler.addCreature.
void Player.Zoo.removeCreature(Creature creature)
References Player.Zoo.corralOf, Player.Zoo.exists, Player.Interface.show.
Referenced by Player.Controler.removeCreature.
void Player.Zoo.kill(Creature creature)
References Player.Zoo.corralOf, Player.Zoo.exists, Player.Interface.show.
Referenced by Player.Controler.kill.
void Player.Zoo.reviveCreature(Creature creature)
References Player.Zoo.corralOf, Player.Zoo.exists, Player.Interface.show.
List< Corral > Player.Zoo.getCorrals()
Referenced by Player.Asker.corral.
List< Creature > Player.Zoo.getCreatures()
References Player.Zoo.corral.
Referenced by Player.Asker.creature.
void Player.Zoo.cooldown(Cooldown cooldown)
References Player.Zoo.cooldown.
Referenced by Player.Zoo.cooldown.
void Player.Zoo.spread(Howl howl)
References Player.Zoo.colony.