Game::Corral::Corral
final int Game.Corral.Corral.MAX
String Game.Corral.Corral.name
Referenced by Game.Corral.Corral.Corral, Game.Corral.Corral.getName, Game.Corral.Aquarium.inaugurate, Game.Corral.Aviary.inaugurate, Game.Corral.Corral.inaugurate.
String Game.Corral.Corral.size
Referenced by Game.Corral.Corral.Corral, Game.Corral.Aquarium.inaugurate, Game.Corral.Aviary.inaugurate, Game.Corral.Corral.inaugurate.
int Game.Corral.Corral.max
Hygiene Game.Corral.Corral.hygiene
Referenced by Game.Corral.Corral.getHygiene.
StorageLevel Game.Corral.Corral.food
Referenced by Game.Corral.Corral.feed.
List<Run> Game.Corral.Corral.creatures
boolean Game.Corral.Corral.isDestroyed
Game.Corral.Corral.Corral(String name, String size)
References Game.Corral.Corral.name, Game.Corral.Corral.size.
ArrayList< Creature > Game.Corral.Corral.completeTable()
Referenced by Game.Corral.Corral.givesFoodToCreature, Game.Corral.Corral.toString.
void Game.Corral.Corral.givesFoodToCreature()
References Game.Corral.Corral.completeTable.
Referenced by Game.Corral.Corral.run.
static Corral Game.Corral.Corral.inaugurate(String name, String size)
Creates and returns a new instance of Corral. name The name of the corral. size The size of the corral. A new Corral instance.
References Game.Corral.Corral.name, Game.Corral.Corral.size.
String Game.Corral.Corral.toString()
References Game.Corral.Corral.completeTable.
void Game.Corral.Corral.addCreature(Creature creature)
Referenced by Game.Corral.Corral.kill.
Creature Game.Corral.Corral.removeCreature(Creature creature)
Referenced by Game.Corral.Corral.kill.
void Game.Corral.Corral.clean()
Hygiene Game.Corral.Corral.getHygiene()
References Game.Corral.Corral.hygiene.
void Game.Corral.Corral.kill(Creature creature)
References Game.Corral.Corral.addCreature, Game.Corral.Corral.removeCreature.
int Game.Corral.Corral.count()
void Game.Corral.Corral.feed()
References Game.Corral.Corral.food.
boolean Game.Corral.Corral.hasFreeSpace()
boolean Game.Corral.Corral.contains(Creature searched)
boolean Game.Corral.Corral.empty()
String Game.Corral.Corral.getName()
Retrieves the name of the corral. The name of the corral.
References Game.Corral.Corral.name.
List< Creature > Game.Corral.Corral.getCreatures()
Retrieves a list of creatures in the corral. A list of creatures.
void Game.Corral.Corral.run()
References Game.Corral.Corral.givesFoodToCreature.
void Game.Corral.Corral.destroy()
boolean Game.Corral.Corral.checkCreature(Creature creature)