Player::Asker
static Sex Player.Asker.sex()
Ask the player to input a sex either MALE or FEMALE The input Sex
References Player.Interface.input, Player.Asker.sex, Player.Interface.show.
Referenced by Player.Creator.createYourCreature, Player.Asker.sex.
static Age Player.Asker.age()
Ask the player to input a correct Age The Age input
static Creature Player.Asker.creature()
Ask the player to choose a creature with an input The chosen creature
References Player.Asker.creature, Player.Zoo.getCreatures, Player.Controler.getInstance, Player.Interface.input, Player.Zoo.showCreatures, Player.Controler.zoo.
Referenced by Player.Asker.creature, Player.Asker.creature.
static Creature Player.Asker.creature(Corral corral)
Ask the player to chose a creature with an input corral A specific corral for the choice to be made The chosen creature
References Player.Asker.corral, Player.Asker.creature, Player.Interface.input.
static Corral Player.Asker.corral()
Ask the player to chose a corral depending on the existing ones The chosen corral
References Player.Asker.corral, Player.Zoo.getCorrals, Player.Controler.getInstance, Player.Interface.input, Player.Controler.zoo.
Referenced by Player.Asker.corral, Player.Asker.creature.