.TH "Application/src/Game/Logic/Cooldown Directory Reference" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Logic/Cooldown Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCooldown\&.java\fP"
.br
.ti -1c
.RI "file \fBCooldownable\&.java\fP"
.br
.ti -1c
.RI "file \fBCooldownType\&.java\fP"
.br
.in -1c
