.TH "Application/src/Game/Lycantropus/Caracteristics Directory Reference" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Lycantropus/Caracteristics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLevel\&.java\fP"
.br
.ti -1c
.RI "file \fBRank\&.java\fP"
.br
.ti -1c
.RI "file \fBStrength\&.java\fP"
.br
.in -1c
