.TH "Application/src/Game/Creature Directory Reference" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Creature Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBBehavior\fP"
.br
.ti -1c
.RI "directory \fBBestiary\fP"
.br
.ti -1c
.RI "directory \fBCaracteristic\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCreature\&.java\fP"
.br
.ti -1c
.RI "file \fBEgg\&.java\fP"
.br
.ti -1c
.RI "file \fBOviparian\&.java\fP"
.br
.ti -1c
.RI "file \fBViviparian\&.java\fP"
.br
.in -1c
