.TH "Application/src/Game/Lycantropus Directory Reference" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Lycantropus Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCaracteristics\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCouple\&.java\fP"
.br
.ti -1c
.RI "file \fBHowl\&.java\fP"
.br
.ti -1c
.RI "file \fBLycantropus\&.java\fP"
.br
.ti -1c
.RI "file \fBPack\&.java\fP"
.br
.in -1c
