.TH "Application/src/Game/Logic/DiceRoll.java" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Logic/DiceRoll.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\&.Logic\&.DiceRoll\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBGame\&.Logic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
