.TH "Game.Lycantropus.Couple" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Couple
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCouple\fP (\fBLycantropus\fP female, \fBLycantropus\fP male)"
.br
.ti -1c
.RI "void \fBreproduce\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game\&.Lycantropus\&.Couple\&.Couple (\fBLycantropus\fP female, \fBLycantropus\fP male)"

.SH "Member Function Documentation"
.PP 
.SS "void Game\&.Lycantropus\&.Couple\&.reproduce ()"

.SS "String Game\&.Lycantropus\&.Couple\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
