.TH "Game.Logic.DiceRoll" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Logic.DiceRoll
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBd4\fP ()"
.br
.ti -1c
.RI "static int \fBd6\fP ()"
.br
.ti -1c
.RI "static int \fBd8\fP ()"
.br
.ti -1c
.RI "static int \fBd12\fP ()"
.br
.ti -1c
.RI "static int \fBd20\fP ()"
.br
.ti -1c
.RI "static int \fBd100\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static int Game\&.Logic\&.DiceRoll\&.d100 ()\fC [static]\fP"

.SS "static int Game\&.Logic\&.DiceRoll\&.d12 ()\fC [static]\fP"

.SS "static int Game\&.Logic\&.DiceRoll\&.d20 ()\fC [static]\fP"

.SS "static int Game\&.Logic\&.DiceRoll\&.d4 ()\fC [static]\fP"

.SS "static int Game\&.Logic\&.DiceRoll\&.d6 ()\fC [static]\fP"

.SS "static int Game\&.Logic\&.DiceRoll\&.d8 ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
