.TH "Game.Lycantropus.Caracteristics.Rank" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Caracteristics.Rank
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRank\fP \fBdowngrade\fP ()"
.br
.ti -1c
.RI "\fBRank\fP \fBupgrade\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBALPHA\fP"
.br
.ti -1c
.RI "\fBBETA\fP"
.br
.ti -1c
.RI "\fBGAMMA\fP"
.br
.ti -1c
.RI "\fBDELTA\fP"
.br
.ti -1c
.RI "\fBEPSILON\fP"
.br
.ti -1c
.RI "\fBZETA\fP"
.br
.ti -1c
.RI "\fBETA\fP"
.br
.ti -1c
.RI "\fBTHETA\fP"
.br
.ti -1c
.RI "\fBIOTA\fP"
.br
.ti -1c
.RI "\fBKAPPA\fP"
.br
.ti -1c
.RI "\fBLAMBDA\fP"
.br
.ti -1c
.RI "\fBMU\fP"
.br
.ti -1c
.RI "\fBNU\fP"
.br
.ti -1c
.RI "\fBXI\fP"
.br
.ti -1c
.RI "\fBOMICRON\fP"
.br
.ti -1c
.RI "\fBPI\fP"
.br
.ti -1c
.RI "\fBRHO\fP"
.br
.ti -1c
.RI "\fBSIGMA\fP"
.br
.ti -1c
.RI "\fBTAU\fP"
.br
.ti -1c
.RI "\fBUPSILON\fP"
.br
.ti -1c
.RI "\fBPHI\fP"
.br
.ti -1c
.RI "\fBCHI\fP"
.br
.ti -1c
.RI "\fBPSI\fP"
.br
.ti -1c
.RI "\fBOMEGA\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBRank\fP Game\&.Lycantropus\&.Caracteristics\&.Rank\&.downgrade ()"

.SS "\fBRank\fP Game\&.Lycantropus\&.Caracteristics\&.Rank\&.upgrade ()"

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.ALPHA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.BETA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.CHI"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.DELTA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.EPSILON"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.ETA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.GAMMA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.IOTA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.KAPPA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.LAMBDA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.MU"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.NU"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.OMEGA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.OMICRON"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.PHI"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.PI"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.PSI"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.RHO"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.SIGMA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.TAU"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.THETA"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.UPSILON"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.XI"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Rank\&.ZETA"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
