.TH "Game.Creature.Caracteristic.Weight" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Weight
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWeight\fP \fBtoSwell\fP ()"
.br
.ti -1c
.RI "\fBWeight\fP \fBtoLoseWeight\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLIGHT\fP"
.br
.ti -1c
.RI "\fBAVERAGE\fP"
.br
.ti -1c
.RI "\fBHEAVY\fP"
.br
.ti -1c
.RI "\fBMASSIVE\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBWeight\fP Game\&.Creature\&.Caracteristic\&.Weight\&.toLoseWeight ()"

.PP
\fBReturns\fP
.RS 4
to the previous width level if it is not already at its lowest 
.RE
.PP

.SS "\fBWeight\fP Game\&.Creature\&.Caracteristic\&.Weight\&.toSwell ()"

.PP
\fBReturns\fP
.RS 4
to the next width level if not already at the top 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Weight\&.AVERAGE"

.SS "Game\&.Creature\&.Caracteristic\&.Weight\&.HEAVY"

.SS "Game\&.Creature\&.Caracteristic\&.Weight\&.LIGHT"

.SS "Game\&.Creature\&.Caracteristic\&.Weight\&.MASSIVE"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
