.TH "Game.Creature.Caracteristic.Sex" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Sex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMALE\fP"
.br
.ti -1c
.RI "\fBFEMALE\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Sex\&.FEMALE"

.SS "Game\&.Creature\&.Caracteristic\&.Sex\&.MALE"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
