.TH "Game.Lycantropus.Howl" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Howl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHowl\fP \fBsetHowler\fP (\fBLycantropus\fP howler)"
.br
.ti -1c
.RI "\fBLycantropus\fP \fBgetHowler\fP ()"
.br
.ti -1c
.RI "\fBHowl\fP \fBsetTarget\fP (\fBLycantropus\fP target)"
.br
.ti -1c
.RI "\fBLycantropus\fP \fBgetTarget\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAGGRESSIVE\fP"
.br
.ti -1c
.RI "\fBBELONGING\fP"
.br
.ti -1c
.RI "\fBSUBMISSION\fP"
.br
.ti -1c
.RI "\fBDOMINATION\fP"
.br
.ti -1c
.RI "\fBANSWER\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBLycantropus\fP Game\&.Lycantropus\&.Howl\&.getHowler ()"

.SS "\fBLycantropus\fP Game\&.Lycantropus\&.Howl\&.getTarget ()"

.SS "\fBHowl\fP Game\&.Lycantropus\&.Howl\&.setHowler (\fBLycantropus\fP howler)"

.SS "\fBHowl\fP Game\&.Lycantropus\&.Howl\&.setTarget (\fBLycantropus\fP target)"

.SS "String Game\&.Lycantropus\&.Howl\&.toString ()"

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Lycantropus\&.Howl\&.AGGRESSIVE"

.SS "Game\&.Lycantropus\&.Howl\&.ANSWER"

.SS "Game\&.Lycantropus\&.Howl\&.BELONGING"

.SS "Game\&.Lycantropus\&.Howl\&.DOMINATION"

.SS "Game\&.Lycantropus\&.Howl\&.SUBMISSION"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
