.TH "Game.Logic.Cooldown.CooldownType" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Logic.Cooldown.CooldownType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBREFRESH\fP"
.br
.ti -1c
.RI "\fBINCUBATION\fP"
.br
.ti -1c
.RI "\fBEND_LOVE_SEASON\fP"
.br
.ti -1c
.RI "\fBSTART_LOVE_SEASON\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Game\&.Logic\&.Cooldown\&.CooldownType\&.END_LOVE_SEASON"

.SS "Game\&.Logic\&.Cooldown\&.CooldownType\&.INCUBATION"

.SS "Game\&.Logic\&.Cooldown\&.CooldownType\&.REFRESH"

.SS "Game\&.Logic\&.Cooldown\&.CooldownType\&.START_LOVE_SEASON"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
