.TH "Game.Lycantropus.Pack" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Pack
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBspread\fP (\fBHowl\fP howl)"
.br
.ti -1c
.RI "boolean \fBcontains\fP (\fBLycantropus\fP lycan)"
.br
.ti -1c
.RI "int \fBdominationOf\fP (\fBLycantropus\fP lycan)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean Game\&.Lycantropus\&.Pack\&.contains (\fBLycantropus\fP lycan)"

.SS "int Game\&.Lycantropus\&.Pack\&.dominationOf (\fBLycantropus\fP lycan)"

.SS "void Game\&.Lycantropus\&.Pack\&.spread (\fBHowl\fP howl)"

.SS "String Game\&.Lycantropus\&.Pack\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
