.TH "Game.Corral.Caracteristic.Hygiene" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Corral.Caracteristic.Hygiene
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHygiene\fP \fBclean\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBAD\fP"
.br
.ti -1c
.RI "\fBCORRECTLY\fP"
.br
.ti -1c
.RI "\fBGOOD\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHygiene\fP Game\&.Corral\&.Caracteristic\&.Hygiene\&.clean ()"

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Corral\&.Caracteristic\&.Hygiene\&.BAD"

.SS "Game\&.Corral\&.Caracteristic\&.Hygiene\&.CORRECTLY"

.SS "Game\&.Corral\&.Caracteristic\&.Hygiene\&.GOOD"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
