.TH "Game.Logic.Cooldown" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Logic.Cooldown
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCooldown\fP"
.br
.ti -1c
.RI "interface \fBCooldownable\fP"
.br
.ti -1c
.RI "enum \fBCooldownType\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
