.TH "Game.Creature.Caracteristic.Health" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Health
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHealth\fP \fBheal\fP ()"
.br
.ti -1c
.RI "\fBHealth\fP \fBloseHealth\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSUFFERING\fP"
.br
.ti -1c
.RI "\fBILL\fP"
.br
.ti -1c
.RI "\fBSKATE\fP"
.br
.ti -1c
.RI "\fBGOOD\fP"
.br
.ti -1c
.RI "\fBVIGOROUS\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHealth\fP Game\&.Creature\&.Caracteristic\&.Health\&.heal ()"

.PP
\fBReturns\fP
.RS 4
to the next level of care if not already at the top 
.RE
.PP

.SS "\fBHealth\fP Game\&.Creature\&.Caracteristic\&.Health\&.loseHealth ()"

.PP
\fBReturns\fP
.RS 4
to the lower care stage if not already at the lowest level 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Health\&.GOOD"

.SS "Game\&.Creature\&.Caracteristic\&.Health\&.ILL"

.SS "Game\&.Creature\&.Caracteristic\&.Health\&.SKATE"

.SS "Game\&.Creature\&.Caracteristic\&.Health\&.SUFFERING"

.SS "Game\&.Creature\&.Caracteristic\&.Health\&.VIGOROUS"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
