.TH "Game.Logic.Cooldown.Cooldownable" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Logic.Cooldown.Cooldownable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcooldown\fP (\fBCooldown\fP cooldown)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Cooldownable interface, implemented by entities that can undergo cooldown\&. Specifies a method to handle cooldown behavior\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Game\&.Logic\&.Cooldown\&.Cooldownable\&.cooldown (\fBCooldown\fP cooldown)"
Initiates a cooldown for the implementing entity\&.
.PP
\fBParameters\fP
.RS 4
\fIcooldown\fP The cooldown duration to be applied\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
