.TH "Game.Creature.Caracteristic.Age" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Age
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAge\fP \fBgettingOder\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBABY\fP"
.br
.ti -1c
.RI "\fBCHILD\fP"
.br
.ti -1c
.RI "\fBTEEN\fP"
.br
.ti -1c
.RI "\fBADULT\fP"
.br
.ti -1c
.RI "\fBELDER\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBAge\fP Game\&.Creature\&.Caracteristic\&.Age\&.gettingOder ()"

.PP
\fBReturns\fP
.RS 4
renvoie le stade de l'age suivant de l'entité\&. Si déjà au dernier stade il meurt\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Age\&.ADULT"

.SS "Game\&.Creature\&.Caracteristic\&.Age\&.BABY"

.SS "Game\&.Creature\&.Caracteristic\&.Age\&.CHILD"

.SS "Game\&.Creature\&.Caracteristic\&.Age\&.ELDER"

.SS "Game\&.Creature\&.Caracteristic\&.Age\&.TEEN"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
