.TH "Game.Creature.Behavior" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Behavior
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBirthBehavior\fP"
.br
.ti -1c
.RI "interface \fBFly\fP"
.br
.ti -1c
.RI "class \fBLaying\fP"
.br
.ti -1c
.RI "class \fBPregnancy\fP"
.br
.ti -1c
.RI "interface \fBRevive\fP"
.br
.ti -1c
.RI "interface \fBRun\fP"
.br
.ti -1c
.RI "interface \fBSwim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
