.TH "Game.Lycantropus.Lycantropus" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Lycantropus
.SH SYNOPSIS
.br
.PP
.PP
Inherits Viviparian, Run, and Runnable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetDomination\fP ()"
.br
.ti -1c
.RI "void \fBhear\fP (\fBHowl\fP howl)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object o)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "Level \fBgetLevel\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLycantropus\fP \fBnewBorn\fP (String name, Sex sex)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean Game\&.Lycantropus\&.Lycantropus\&.equals (Object o)"

.SS "int Game\&.Lycantropus\&.Lycantropus\&.getDomination ()"

.SS "Level Game\&.Lycantropus\&.Lycantropus\&.getLevel ()"

.SS "void Game\&.Lycantropus\&.Lycantropus\&.hear (\fBHowl\fP howl)"

.SS "static \fBLycantropus\fP Game\&.Lycantropus\&.Lycantropus\&.newBorn (String name, Sex sex)\fC [static]\fP"

.SS "void Game\&.Lycantropus\&.Lycantropus\&.run ()"

.SS "String Game\&.Lycantropus\&.Lycantropus\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
