.TH "Game.Creature.Caracteristic.Hunger" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Hunger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHunger\fP \fBeat\fP ()"
.br
.ti -1c
.RI "\fBHunger\fP \fBtoBeHungry\fP ()"
.br
.ti -1c
.RI "boolean \fBisHungry\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSTARVING\fP"
.br
.ti -1c
.RI "\fBHUNGRY\fP"
.br
.ti -1c
.RI "\fBGOOD\fP"
.br
.ti -1c
.RI "\fBMEALS\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHunger\fP Game\&.Creature\&.Caracteristic\&.Hunger\&.eat ()"

.PP
\fBReturns\fP
.RS 4
renvoie le stade de faim inférieur 
.RE
.PP

.SS "boolean Game\&.Creature\&.Caracteristic\&.Hunger\&.isHungry ()"

.SS "\fBHunger\fP Game\&.Creature\&.Caracteristic\&.Hunger\&.toBeHungry ()"

.PP
\fBReturns\fP
.RS 4
renvoie le stade de faim supérieur 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Hunger\&.GOOD"

.SS "Game\&.Creature\&.Caracteristic\&.Hunger\&.HUNGRY"

.SS "Game\&.Creature\&.Caracteristic\&.Hunger\&.MEALS"

.SS "Game\&.Creature\&.Caracteristic\&.Hunger\&.STARVING"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
