.TH "Game.Creature.Behavior.Revive" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Behavior.Revive
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The Revive interface, implemented by creatures that can revive Used to give a common type 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
