.TH "Game.Creature.Caracteristic" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBAge\fP"
.br
.ti -1c
.RI "enum \fBFatigue\fP"
.br
.ti -1c
.RI "enum \fBHealth\fP"
.br
.ti -1c
.RI "enum \fBHeight\fP"
.br
.ti -1c
.RI "enum \fBHunger\fP"
.br
.ti -1c
.RI "enum \fBSex\fP"
.br
.ti -1c
.RI "enum \fBStorageLevel\fP"
.br
.ti -1c
.RI "enum \fBWeight\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
