.TH "Game.Corral.Caracteristic" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Corral.Caracteristic
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBHygiene\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
