.TH "Game.Lycantropus.Caracteristics.Level" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Caracteristics.Level
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBbeat\fP (\fBLevel\fP foe)"
.br
.ti -1c
.RI "\fBLevel\fP \fBset\fP (Sex sex, Age age, \fBStrength\fP strength, \fBRank\fP rank)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSTRONG\fP"
.br
.ti -1c
.RI "\fBFRAGILE\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean Game\&.Lycantropus\&.Caracteristics\&.Level\&.beat (\fBLevel\fP foe)"

.SS "\fBLevel\fP Game\&.Lycantropus\&.Caracteristics\&.Level\&.set (Sex sex, Age age, \fBStrength\fP strength, \fBRank\fP rank)"

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Lycantropus\&.Caracteristics\&.Level\&.FRAGILE"

.SS "Game\&.Lycantropus\&.Caracteristics\&.Level\&.STRONG"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
