.TH "Game.Creature.Bestiary" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Bestiary
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDragon\fP"
.br
.ti -1c
.RI "class \fBKraken\fP"
.br
.ti -1c
.RI "class \fBMegalodon\fP"
.br
.ti -1c
.RI "class \fBMermaid\fP"
.br
.ti -1c
.RI "class \fBNymph\fP"
.br
.ti -1c
.RI "class \fBPhenix\fP"
.br
.ti -1c
.RI "class \fBUnicorn\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
