.TH "Game.Creature.Behavior.Laying" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Behavior.Laying
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGame\&.Creature\&.Behavior\&.BirthBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBmakeBaby\fP (\fBCreature\fP baby, \fBCreature\fP parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Laying behavior, used by Oviparrian Allows a creature to lay eggs 
.SH "Member Function Documentation"
.PP 
.SS "void Game\&.Creature\&.Behavior\&.Laying\&.makeBaby (\fBCreature\fP baby, \fBCreature\fP parent)"

.PP
Reimplemented from \fBGame\&.Creature\&.Behavior\&.BirthBehavior\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
