.TH "Game.Lycantropus.Caracteristics" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Lycantropus.Caracteristics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBLevel\fP"
.br
.ti -1c
.RI "enum \fBRank\fP"
.br
.ti -1c
.RI "enum \fBStrength\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
