.TH "Game.Creature.Behavior.Fly" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Behavior.Fly
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The Fly interface, implemented by any flying creature Used to give a common type 

.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
