.TH "Game.Creature.Viviparian" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Viviparian
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGame\&.Creature\&.Creature\fP\&.
.PP
Inherited by \fBGame\&.Creature\&.Bestiary\&.Mermaid\fP, \fBGame\&.Creature\&.Bestiary\&.Nymph\fP, and \fBGame\&.Creature\&.Bestiary\&.Unicorn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViviparian\fP (String \fBname\fP, Sex \fBsex\fP, Weight \fBweight\fP, Height \fBheight\fP, Age \fBage\fP, Hunger \fBhunger\fP, Fatigue \fBfatigue\fP, Health \fBhealth\fP)"
.br
.in -1c

Public Member Functions inherited from \fBGame\&.Creature\&.Creature\fP
.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBeat\fP ()"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "Sex \fBgetSex\fP ()"
.br
.ti -1c
.RI "Hunger \fBgetHunger\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object o)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBGame\&.Creature\&.Creature\fP
.in +1c
.ti -1c
.RI "BirthBehavior \fBbirthingBehavior\fP"
.br
.in -1c

Protected Member Functions inherited from \fBGame\&.Creature\&.Creature\fP
.in +1c
.ti -1c
.RI "\fBCreature\fP (String \fBname\fP, Sex \fBsex\fP, Weight \fBweight\fP, Height \fBheight\fP, Age \fBage\fP, Hunger \fBhunger\fP, Fatigue \fBfatigue\fP, Health \fBhealth\fP)"
.br
.ti -1c
.RI "void \fBtoFly\fP ()"
.br
.RI "Behavior\&. "
.ti -1c
.RI "void \fBtoRun\fP ()"
.br
.ti -1c
.RI "void \fBtoSwim\fP ()"
.br
.ti -1c
.RI "void \fBtoBeHungry\fP ()"
.br
.ti -1c
.RI "void \fBshout\fP ()"
.br
.ti -1c
.RI "void \fBloseHealth\fP ()"
.br
.ti -1c
.RI "void \fBheal\fP ()"
.br
.ti -1c
.RI "void \fBgettingFatigue\fP ()"
.br
.ti -1c
.RI "void \fBsleep\fP ()"
.br
.ti -1c
.RI "void \fBage\fP ()"
.br
.ti -1c
.RI "void \fBgrowUp\fP ()"
.br
.ti -1c
.RI "void \fBtoSwell\fP ()"
.br
.ti -1c
.RI "void \fBtoLoseWeight\fP ()"
.br
.ti -1c
.RI "void \fBreproduce\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBGame\&.Creature\&.Creature\fP
.in +1c
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "Sex \fBsex\fP"
.br
.ti -1c
.RI "Weight \fBweight\fP"
.br
.ti -1c
.RI "Height \fBheight\fP"
.br
.ti -1c
.RI "Age \fBage\fP"
.br
.ti -1c
.RI "Hunger \fBhunger\fP"
.br
.ti -1c
.RI "Fatigue \fBfatigue\fP"
.br
.ti -1c
.RI "Health \fBhealth\fP"
.br
.ti -1c
.RI "boolean \fBisAlive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an Viviparian Extends the Creature class\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Game\&.Creature\&.Viviparian\&.Viviparian (String name, Sex sex, Weight weight, Height height, Age age, Hunger hunger, Fatigue fatigue, Health health)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
