.TH "Game.Creature.Caracteristic.Height" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game.Creature.Caracteristic.Height
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHeight\fP \fBgrowUp\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSMALL\fP"
.br
.ti -1c
.RI "\fBAVERAGE\fP"
.br
.ti -1c
.RI "\fBBIG\fP"
.br
.ti -1c
.RI "\fBHUMONGOUS\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBHeight\fP Game\&.Creature\&.Caracteristic\&.Height\&.growUp ()"

.PP
\fBReturns\fP
.RS 4
to the highest stage if not already at the top 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Game\&.Creature\&.Caracteristic\&.Height\&.AVERAGE"

.SS "Game\&.Creature\&.Caracteristic\&.Height\&.BIG"

.SS "Game\&.Creature\&.Caracteristic\&.Height\&.HUMONGOUS"

.SS "Game\&.Creature\&.Caracteristic\&.Height\&.SMALL"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
