.TH "Application/src/Game/Corral/Caracteristic/Hygiene.java" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Corral/Caracteristic/Hygiene.java
.SH SYNOPSIS
.br
.PP
\fCimport Player\&.Controler;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBGame\&.Corral\&.Caracteristic\&.Hygiene\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBGame\&.Corral\&.Caracteristic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
