.TH "Application/src/Game/Creature/Bestiary/Kraken.java" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Creature/Bestiary/Kraken.java
.SH SYNOPSIS
.br
.PP
\fCimport Game\&.Creature\&.Behavior\&.Swim;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\&.Creature\&.Bestiary\&.Kraken\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBGame\&.Creature\&.Bestiary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
