.TH "Application/src/Game/Lycantropus/Caracteristics/Level.java" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Lycantropus/Caracteristics/Level.java
.SH SYNOPSIS
.br
.PP
\fCimport Game\&.Creature\&.Caracteristic\&.Age;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBGame\&.Lycantropus\&.Caracteristics\&.Level\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBGame\&.Lycantropus\&.Caracteristics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
