.TH "md__r_e_a_d_m_e" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- zooFantastique 
.PP
Ceci est un projet étudiant réalisé en groupe de 3 dans le cadre de la ressource R3\&.04\&.
.PP
\fI\fBZoo Fantastique\fP\fP est un jeu de gestion de créatures fantastiques\&. 
.br
.PP
Lancez l'application depuis \fBPlayer\&.Zoo\fP et testez dans votre terminal cette version de la simulation de Zoo ! L'interface vous guidera sur les commandes à entrer\&. 
.br
.PP
A venir : La gestion de meutes de loups-garoux \&.\&.\&. 
