.TH "Application/src/Game/Lycantropus/Pack.java" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application/src/Game/Lycantropus/Pack.java
.SH SYNOPSIS
.br
.PP
\fCimport java\&.util\&.List;\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\&.Lycantropus\&.Pack\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBGame\&.Lycantropus\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
