.TH "Player.Interface" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Interface
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBshow\fP (String string)"
.br
.ti -1c
.RI "static String \fBinput\fP (String string)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides basic interaction methods for input and output\&. 
.SH "Member Function Documentation"
.PP 
.SS "static String Player\&.Interface\&.input (String string)\fC [static]\fP"
Takes user input after displaying the provided string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string prompt for user input\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The user input as a string\&. 
.RE
.PP

.SS "static void Player\&.Interface\&.show (String string)\fC [static]\fP"
Displays the provided string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to display\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
