.TH "Player.Creator" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Creator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBZoo\fP \fBcreateYourZoo\fP ()"
.br
.ti -1c
.RI "static Creature \fBcreateYourCreature\fP (Corral corral)"
.br
.ti -1c
.RI "static Corral \fBcreateYourCorral\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Creator interact with the player to create anything\&. 
.br
 Has only a bunch of usefulle static methods\&. 
.SH "Member Function Documentation"
.PP 
.SS "static Corral Player\&.Creator\&.createYourCorral ()\fC [static]\fP"

.SS "static Creature Player\&.Creator\&.createYourCreature (Corral corral)\fC [static]\fP"

.SS "static \fBZoo\fP Player\&.Creator\&.createYourZoo ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
