.TH "Player.ZooMaster" 3 "Version 1.0" "Zoo Fantastique" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.ZooMaster
.SH SYNOPSIS
.br
.PP
.PP
Inherits Cooldownable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBZooMaster\fP (String name, Sex sex, Age age)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "void \fBcooldown\fP (Cooldown cooldown)"
.br
.ti -1c
.RI "void \fBoptions\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the ZooMaster, controlling actions in the zoo\&. Implements Cooldownable interface for managing cooldowns\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Player\&.ZooMaster\&.ZooMaster (String name, Sex sex, Age age)"

.SH "Member Function Documentation"
.PP 
.SS "void Player\&.ZooMaster\&.cooldown (Cooldown cooldown)"

.SS "void Player\&.ZooMaster\&.options ()"

.SS "String Player\&.ZooMaster\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Zoo Fantastique from the source code\&.
